services:
  fastapi-app:
    build: . 
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - fastapi-app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge